### ISSUE TITLE
`_parse': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by omerkaptan** [yulrizka/trakt-imdb-importer#9]
Traceback (most recent call last):
        8: from import.rb:67:in `<main>'
        7: from import.rb:67:in `each_slice'
        6: from C:/tools/ruby27/lib/ruby/2.7.0/csv/table.rb:337:in `each'
        5: from C:/tools/ruby27/lib/ruby/2.7.0/csv/table.rb:337:in `each'
        4: from import.rb:73:in `block in <main>'
        3: from import.rb:73:in `each'
        2: from import.rb:75:in `block (2 levels) in <main>'
        1: from C:/tools/ruby27/lib/ruby/2.7.0/time.rb:372:in `parse'
C:/tools/ruby27/lib/ruby/2.7.0/time.rb:372:in `_parse': no implicit conversion of nil into String (TypeError)

**Comment by TheSoulrester** [comment]
i have the same issue :(

**Comment by wisdomtooth** [comment]
Same here.
